### ISSUE TITLE
Conflict with Advanced XRay (Fabric Edition)

### ISSUE THREAD

**Issue by LOLboy199** [BurritoBandit28/Useful-Widgets#1]
For whatever reason having the mod Advanced XRay (Fabric Edition) makes it to where none of the link buttons in the menu work at all. Everything else from Useful Widgets seems to load and work fine (reloading the menu, the icons textures, and buttons), but pressing any of the link buttons will do nothing at all. 

I don't really know much about coding at all, but I'm trying my best to look into what the conflict is. 
Here are the links for the other mod's curseforge and gethub:

https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition

https://github.com/MichaelHillcox/XRay-Fabric

Please let me know if I can do anything to help resolve this issue, and thank you in advance.

**Comment by BurritoBandit28** [comment]
I'm afraid I haven't been able to recreate this issue, can you send me your config file or a screenshot of it?

**Comment by LOLboy199** [comment]
I had to convert the files to .txt since the Widgets file was .properties and the Advanced-Xray files were .json

Here is the Useful Widgets file:
[config.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936396/config.txt)

Here are the Xray files:
[blocks.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936400/blocks.txt)
[settings.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936401/settings.txt)

**Comment by LOLboy199** [comment]
Okay idk why I didn't think of deleting the Advanced xray files and letting the game recreate them before... I'm looking into that now and it seems to be somehting in the blocks.json file. 
The new blocks file that it created worked fine, but copying the old text into that file broke the mod again.
I'm looking now to see if creating any file will break it or if it happens on restart or what. Should just take me a few minutes.

**Comment by LOLboy199** [comment]
Okay so once any block is added to the Advanced Xray blocks.json config file and the game is restarted then the Useful Widgets mod links no longer work.

**Comment by LOLboy199** [comment]
[blocks.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936542/blocks.txt)

Here is that same file but with a lot less clutter if it helps to look at this instead of the one I sent before.

**Comment by BurritoBandit28** [comment]
This bug seems rather odd. Tomorrow I will have a closer look and try and see where they conflict, although on first glance (of the source code) I couldn't see any clear problems. I'll look again more thoroughly.

**Comment by LOLboy199** [comment]
Interesting. Thanks so much for looking into it!

**Comment by BurritoBandit28** [comment]
> I had to convert the files to .txt since the Widgets file was .properties and the Advanced-Xray files were .json
> 
> Here is the Useful Widgets file: [config.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936396/config.txt)
> 
> Here are the Xray files: [blocks.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936400/blocks.txt) [settings.txt](https://github.com/BurritoBandit28/Useful-Widgets/files/7936401/settings.txt)

Okay I have just tried out the files you have sent me (these ones), and everything seems to be working just fine for me. I don't know what was causing your issue but as I can't recreate it I'm going to have to mark it as closed. Thanks for reporting this bug though, its appreciated that you'd take time to try and find the error with my mod.

**Comment by LOLboy199** [comment]
Thanks anyways 😔
If I find the actual cause you may hear more from me
